name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  docker_build:
    uses: "philipcristiano/workflows/.github/workflows/docker-build.yml@main"
    with:
      docker_platforms: linux/amd64
      timeout: 120
