name: Main Branch Deploy

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:

  docker_push:
    name: "Push docker image"
    uses: "philipcristiano/workflows/.github/workflows/docker-build-push.yml@main"

    with:
      repository: philipcristiano/electrs
      qemu_platforms: amd64,arm64
      docker_platforms: linux/amd64,linux/arm64/v8
      timeout: 60

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
